{
    'name': 'School Management',
    'version': '19.0.1.0.0',
    'summary': 'Manage students, teachers, classes, exams and fees',
    'description': 'Complete school management system for Odoo 19',
    'author': 'Panha Koeun',
    'category': 'School',
    'depends': ['base'],
    'data': [
        'security/school_security.xml',
        'security/ir.model.access.csv',
        'data/demo_data.xml',
        'views/student_views.xml',
        'views/teacher_views.xml',
        'views/class_views.xml',
        'views/subject_views.xml',
        'views/attendance_views.xml',
        'views/exam_views.xml',
        'views/grade_views.xml',
        'views/fee_views.xml',
        'views/menu.xml',
    ],
    'demo': ['data/demo_data.xml'],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}