[options]
admin_passwd = admin
addons_path = /app/addons,/app/custom,/app/odoo/addons
proxy_mode = True
http_port = 8069
db_maxconn = 16
max_cron_threads = 1
limit_time_cpu = 60
limit_time_real = 120
