from . import state_notification
from . import student
from . import teacher
from . import school_class
from . import certificate
from . import subject
from . import enrollment
from . import attendance
from . import exam
from . import grade
from . import fee
from . import major
from . import dashboard
from . import year_payment
from . import timetable
from . import teaching_assignment
from . import student_subject
from . import permission
from . import feedback
